# Copyright 2023 The Protobom Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Set tag name
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 1

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: './.go-version'
          check-latest: true

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@a30d93cf2aa029e1e4c8a6c79f766aebf429fddb # v0.3.1

      - name: Generate SBOM
        shell: bash
        run: |
          bom generate --format=json -o /tmp/protobom-$TAG.spdx.json .

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@a30d93cf2aa029e1e4c8a6c79f766aebf429fddb # v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: "/tmp/protobom-$TAG.spdx.json"
          sbom: false
